### ISSUE TITLE
感谢作者分享。请问能否分享finetune过的ROP model

### ISSUE THREAD

**Issue by LLLLucensus** [chongzhangFDU/ROOR#3]

**Comment by chongzhangFDU** [comment]
We apologize that due to the policies of the affiliated organization of the authors, we are currently unavailable to release the fine-tuned weights. If you find any trouble to re-implement the experiment results, please contact: chongzhang20@fudan.edu.cn.
抱歉因为单位政策，我们暂时无法发布微调后的权重。如果您在复现实验结果时发现任何问题，请联系chongzhang20@fudan.edu.cn.
